[package]
name = "fastrss"
version = "0.3.0"
authors = []
edition = "2018"

[lib]
name = "fastrss"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.4"
rss = {git = "https://github.com/simplecastapps/rss", features = ["serde"], default-features = false}
serde = "1.0.104"
serde_json = "1.0.48"
serde_rustler = "0.1.0"
serde-transcode = "1.1.0"
